spring.application.name=test

# Cloud Run provides PORT=8080
server.port=${PORT:8084}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.exam.max-violations-before-auto-submit=3

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=43200000

app.jwt.cookie.secure=${COOKIE_SECURE:false}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs